/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef SKNEWPDF
#define SKNEWPDF

#include "RooAbsPdf.h"
#include "RooHSEventsPDF.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class SKNewPDF : public RooHSEventsPDF {
public:
  SKNewPDF() {} ; 
  SKNewPDF(const char *name, const char *title,
	      RooAbsReal& _cosThetaKpHel,
	      RooAbsReal& _phiKpHel,
	      RooAbsReal& _PHI,
	      RooAbsReal& _pol:polState,
	      RooAbsReal& _rho000,
	      RooAbsReal& _Rerho010,
	      RooAbsReal& _rho00m1,
	      RooAbsReal& _rho111,
	      RooAbsReal& _rho100,
	      RooAbsReal& _Rerho110,
	      RooAbsReal& _rho11m1,
	      RooAbsReal& _Imrho210,
	      RooAbsReal& _Imrho21m1);
  SKNewPDF(const SKNewPDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new SKNewPDF(*this,newname); }
  inline virtual ~SKNewPDF() { }

protected:
  Double_t fMCcosThetaKpHel;
  Double_t fMCphiKpHel;
  Double_t fMCPHI;
  Double_t fMCpol:polState;

  RooRealProxy cosThetaKpHel ;
  RooRealProxy phiKpHel ;
  RooRealProxy PHI ;
  RooRealProxy pol:polState ;
  RooRealProxy rho000 ;
  RooRealProxy Rerho010 ;
  RooRealProxy rho00m1 ;
  RooRealProxy rho111 ;
  RooRealProxy rho100 ;
  RooRealProxy Rerho110 ;
  RooRealProxy rho11m1 ;
  RooRealProxy Imrho210 ;
  RooRealProxy Imrho21m1 ;
  
  Double_t evaluate() const ;
  Double_t evaluateMC() const ;
  void MakeSets();

private:

  ClassDef(SKNewPDF,1) // Your description goes here...
};
 
#endif
